// All confab members
const confab = [
    'Indira Balkasoon',
    'Becky Birch',
    'Daniel Blank',
    'John Butler',
    'Nick Clapp',
    'Paul Coen',
    'Jim Cousins',
    'Paul Engleman',
    'Jim Ettore',
    'Court Federle',
    'Jim Holik',
    'Nancy Israel',
    'Bob Lee',
    'David Keehn',
    'Don Kent', 
    'Margaret Manos',
    'Mark McCullough',
    'Eric Milton',
    'Becca Mudge',
    'Jim Oppenheim',
    'Peter Ory',
    'Tom Pastore',
    'Seth Perlman',
    'Chuck Savage',
    'Hank Seifert',
    'Jim Simon',
    'Debora Stern',
    'Peter Strugatz',
    'David Turanski'
]
